x-common-params:
  - &docker-container
    docker#v3.8.0:
      image: "public.ecr.aws/automattic/android-build-image:v1.3.0"
      propagate-environment: true
      environment:
       # DO NOT MANUALLY SET THESE VALUES!
        # They are passed from the Buildkite agent to the Docker container
        - "AWS_ACCESS_KEY"
        - "AWS_SECRET_KEY"
  - &nvm_plugin
    automattic/nvm#0.3.0:

steps:
  - label: "Publish to Maven Local (to verify build)"
    command: |
      npm install
      ./gradlew publishToMavenLocal
    plugins:
      - *docker-container
      - *nvm_plugin
  - label: "Publish to S3"
    plugins:
      - *docker-container
      - *nvm_plugin
    if: build.branch == "trunk"
    command: |
      npm install

      .buildkite/publish-libraries.sh
