agents: { queue: "android" }

x-common-params:
  - &ci_toolkit
      automattic/a8c-ci-toolkit#3.0.1
  - &nvm_plugin
    automattic/nvm#0.3.0:
      # This is an attempt to fix curl error (92) during installing nodejs.
      curlrc: --http1.1

steps:
  - label: "Publish to Maven Local (to verify build)"
    command: |
      ls -la $(which sdkmanager)
      sdkmanager --install "ndk;23.1.7779620"
      npm install
      ./gradlew publishToMavenLocal
    plugins:
      - *ci_toolkit
      - *nvm_plugin
  - label: "Publish to S3"
    plugins:
      - *ci_toolkit
      - *nvm_plugin
    if: build.branch == "trunk"
    command: |
      sdkmanager --install "ndk;23.1.7779620"
      npm install
      .buildkite/publish-libraries.sh
