common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Publish to S3"
    plugins: *common_plugins
    command: |
      source /root/.bashrc
      nvm install && nvm use
      npm install

      .buildkite/publish-libraries.sh
